language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: 1r1Jz19+VFl7hAf+wYU8rXEo2scrjZrd15GkBJN8cb2tu/AcsTrANKb8xM9cu5dzhxULzN7Zp2TOOPyr8vXxoLBqbMTzWNB+wV0XJ3QqLCr7+dXX9ERKsWGmzZVQ4F0HLRlLWnSwIX6mC0FPj1ABgRtfYdjMykpp9Lr+fyadAbbB64EwYv6jcgOMTegG0QXO9JN173zm/rccxDBb2KZomu/nFbtxtu/vrKucxwTSLyAPF4GaeK1opMAQEnI88N4kM+1+NyLU7E0aHc8ZD9o1NJreaSipI1ss3IucKHT5IzZcDthIGVeB+emSkuLTGp0OZJUgGYc+/FMfcbnHszmJhebRFa4O52ZYbYDAs9mpnTQ3h6E5PmNgZBYV/8C5nq/jvZFvjegGluD5CUlTg5H6g1R73VccRcgMVwH6EZsjHVZCevT54LxzlHd8mqgFseM0oO4S2fDC4PKbzZpdWDjOdh6L8PBUlW+KFD3bE7aQHq7FMVkYGaEo5xKFgsNY/hw9r/K2fKvyU8rIGsa/2qiOHXZSt42gaNXQnECQ45Laf5abLgrgUfmBma9R2bjfj1Kq8aPWeqKiUgkIFS6+cSjbqmEJYMtMn1laeQFnFVB3OhDLIke96b9MS5XoTsDD12Hk92mkQWy8Rc0N25asYBSbkeZsBhtbQDceI8EZutUJcPA=
