language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "jrPezs25z1KuelzOoQOvogEHchVQGSSEGVuTCKm9N513FgMBSkZqDSjXPCtfxX3nqjdOqDykwA+DwJgMhEosiDN678Cm4Nx24y36Gh9+sGosfkEPBJjNHZYctMDdE1Mxb1uBX0dn3Jx7hCZ9gpd+JK7Wbh/Mx4iXSort1nsouzetGUYYP8WwvVKiOd7+2mSszj279miE3vAa2qBLNysEzcbOPpnsUd5YGrFFOyzbdblLu5j2P7GJccr6NTTVfpiTJL14e6r3oQlo8m295FjKwYBqrS5mPk7+kpxTLKZrQnFXsNrjUZTxvNBNSv+PAdv2vErDpZeJmjJOEW6v7QDeDflmJVS+pyKPwA92VV17r66UwDnhNNaGojXT6sQaddfTA18AUlAj2qrbZpXO/PVfJGrxwU9obrzenWgzpixKggq/nPbcw8VFHdzkt1Id6jGbz+h1jFCowl5LWZcdHi5j8zdiuV0tD4amT+TxAMBbGwQWiKuC3VCccoFpo1LEORPYFQcCrOmntWEYjXbf9SonQrC+BkiuFuthBAVNATlj6RefmZGUZTj+Zq9LL3mArOTfOYb3+K5oZOsZECucaqfHiRdfZBMpLWQREl7QkNncgKqeYWepkTDVtIKzDGe7fVbEMVRS0rmuZF4fZ8XeiRH1zE9xC2EckS7iPIK0wRH6Vfg="
